service: api-template-${sls:stage}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getMethod:
    handler: src/getMethod.handler
    events:
      - httpApi: GET /

plugins:
  - serverless-offline
  - serverless-esbuild
