service: api-template-${sls:stage}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  getMethod:
    handler: src/getMethod.handler
    events:
      - httpApi: GET /examples

plugins:
  - serverless-offline
  - serverless-esbuild
